In [2]:
import numpy as np
import pandas as pd

In [3]:
dict = {
    "name":["bhawani","bhuvan","divyansh","dhruv", "dipanshu"],
        "age":[20,20,21,20,20],
        "height":[5.11,5.8,5.9,5.8,5.9],
        "weight":[65, 67,62,63,70],
        "grade":["A","A", "A","A","A"],
}
df = pd.DataFrame(dict)
print(df)

       name  age  height  weight grade
0   bhawani   20    5.11      65     A
1    bhuvan   20    5.80      67     A
2  divyansh   21    5.90      62     A
3     dhruv   20    5.80      63     A
4  dipanshu   20    5.90      70     A

In [4]:
df.shape

(5, 5)

In [5]:
df.columns

Index(['name', 'age', 'height', 'weight', 'grade'], dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   height  5 non-null      float64
 3   weight  5 non-null      int64
 4   grade   5 non-null      str
dtypes: float64(1), int64(2), str(2)
memory usage: 332.0 bytes

In [9]:
df.describe()

             age    height     weight
count   5.000000  5.000000   5.000000
mean   20.200000  5.702000  65.400000
std     0.447214  0.334694   3.209361
min    20.000000  5.110000  62.000000
25%    20.000000  5.800000  63.000000
50%    20.000000  5.800000  65.000000
75%    20.000000  5.900000  67.000000
max    21.000000  5.900000  70.000000

In [ ]:
df["age"] +10

0    30
1    30
2    31
3    30
4    30
Name: age, dtype: int64

Data Function Application

In [11]:
df

       name  age  height  weight grade
0   bhawani   20    5.11      65     A
1    bhuvan   20    5.80      67     A
2  divyansh   21    5.90      62     A
3     dhruv   20    5.80      63     A
4  dipanshu   20    5.90      70     A

In [12]:
def square(x):
    return x **2

In [14]:
df['age']=df['age'].apply(square)

In [15]:
df

       name  age  height  weight grade
0   bhawani  400    5.11      65     A
1    bhuvan  400    5.80      67     A
2  divyansh  441    5.90      62     A
3     dhruv  400    5.80      63     A
4  dipanshu  400    5.90      70     A